/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as automationRegistryInterface12Sol from "./AutomationRegistryInterface1_2.sol";
export type { automationRegistryInterface12Sol };
export type { AutomationCompatibleInterface } from "./AutomationCompatibleInterface";
export type { LinkTokenInterface } from "./LinkTokenInterface";
