/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AutomationRegistryBaseInterface } from "./AutomationRegistryBaseInterface";
export type { AutomationRegistryExecutableInterface } from "./AutomationRegistryExecutableInterface";
export type { AutomationRegistryInterface } from "./AutomationRegistryInterface";
